rename: wf files

diff --git a/.github/workflows/common_tf_test.yml b/.github/workflows/common_tf_test.yml
--- a/.github/workflows/common_tf_test.yml
+++ b/.github/workflows/common_tf_test.yml
@@ -1,17 +1,46 @@
 name: COMMON_TF_TEST
 
 on:
+  pull_request:
+    branches:
+      # PRでmainブランチへマージ時に実行する。
+      - main
   push:
     branches:
-      - develop
-      
+      # 開発ブランチにpushされた場合に実行する。
+      - '**/issue-[0-9]+'
+    paths-ignore:
+      # ETagの更新ではワークフローは実行しない
+      - '**/**/**/etag-tfstate.txt'
+      # モジュールのみの更新では実行しない。
+      - 'modules/**/**'
+
 permissions: 
       id-token: write
+      pull-requests: write
       
 jobs:
+  isIssueExsit:
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    steps:
+      - name: Check if the issue exists.
+        id: chkIssue
+        if: github.event_name == 'push'
+        run: |
+          export ISSUE_NUM=$(echo ${{ github.event.ref }} | awk -F'/' '{print $NF}' | sed -r -e 's/^issue-([0-9]+)$/\1/')
+          HTTP_STATE=$(curl -s -I -u ${{ github.event.sender.login }}:${{ secrets.GH_PAT }} \
+              -H "Accept: application/vnd.github.v3+json" \
+              -o /dev/null -w '%{http_code}\n' \
+              https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUM})
+          if [ ${HTTP_STATE} -ne 200 ]; then
+            echo "${{ github.repository }}/issues/${ISSUE_NUM} is not found."
+            exit 1
+          fi
   # 複数のディレクトリに対して効率よくテストを行うため、対象ディレクトリを抽出する。
   directories:
     runs-on: ubuntu-latest
+    needs: isIssueExsit
     outputs:
       dir: ${{ steps.set-dirs.outputs.dir }}
     steps:
@@ -20,7 +49,7 @@ jobs:
         with:
           token: ${{ secrets.GH_PAT }}
       - id: set-dirs
-        run: echo "::set-output name=dir::$(ls -d */*/ | jq -R -s -c 'split("\n")[:-1]')"
+        run: echo "::set-output name=dir::$(ls -d */*/*/ | jq -R -s -c 'split("\n")[:-1]')"
 
   commonTest:
     runs-on: ubuntu-latest
@@ -28,29 +57,74 @@ jobs:
     timeout-minutes: 5
     strategy:
       matrix:
+        # ["ec2/prod/app_server/","vpc/prod/subnet/"]
         dir: ${{fromJson(needs.directories.outputs.dir)}}
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           token: ${{ secrets.GH_PAT }}
-    
-      # 前回のコミットと差分がなければスキップ
+        
+      # ルートディレクトリの.tfファイルに、前回のコミットと差分がなければスキップ
       - name: Check diff
         id: diff
         uses: technote-space/get-diff-action@v4.0.2
         with:
           GITHUB_TOKEN: ${{ secrets.GH_PAT }}
           PATTERNS: |
-            ${{ matrix.dir }}/modules/**/*.tf
-            ${{ matrix.dir }}/*.tf
+            ${{ matrix.dir }}*.tf
       
+      # terraform plan等の実行結果を投稿する先となるPRを検索
+      - name: Find current pull request
+        id: findPr
+        if: steps.diff.outputs.diff
+        uses: jwalton/gh-find-current-pr@v1
+        with:
+          state: all
+    
       - name: Configure AWS Credentials
         if: steps.diff.outputs.diff
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-region: ap-northeast-1
           role-to-assume: arn:aws:iam::166313796795:role/test-gha
+
+      # PR時のみ。
+      # tfstateファイルがテスト～承認までの間に変更されていないことを担保するため、s3に保存したtfstateファイルのETagを利用する。
+      # ETagに差があれば、ワークフローを失敗させる。
+      # aws cli のオプションにETagを付与してhttpで変更を確認する方法は、出力のパース等が必要なため、単純なファイル比較とする。
+      - name: Check ETag
+        id: chkETag
+        if: steps.diff.outputs.diff && github.event_name == 'pull_request'
+        working-directory: ${{ matrix.dir }}
+        run: |
+          mv ./etag-tfstate.txt{,.old}
+          aws s3api head-object --bucket miyashita-tfstate --key ${{ github.repository }}/${{ matrix.dir }}terraform.tfstate | jq -r .ETag > ./etag-tfstate.txt
+          diff -u ./etag-tfstate.txt.old ./etag-tfstate.txt
+          if [ $? -ne 0 ]; then
+            echo "The ETag has changed since the last check."
+            exit 1
+          fi
+
+      # push時のみ。
+      # 各tfstateファイルのETagを出力。
+      # tfstateファイルがなければ（新規）空ファイルが生成される。
+      # ETagファイルをコミットする。
+      - name: Store ETag of tfstate file
+        id: storeETag
+        if: steps.diff.outputs.diff  && github.event_name == 'push'
+        working-directory: ${{ matrix.dir }}
+        run: |
+          aws s3api head-object --bucket miyashita-tfstate --key ${{ github.repository }}/${{ matrix.dir }}terraform.tfstate | jq -r .ETag > ./etag-tfstate.txt
+          cat ./etag-tfstate.txt
+          changes=$(git status -s | wc -l)
+          if [ $changes -gt 0 ]; then
+            git config --local user.email  ${{ github.event.pusher.email }}
+            git config --local user.name  ${{ github.event.pusher.name }}
+            git add ./etag-tfstate.txt
+            git commit -m "add: Store ETag of tfstate file"
+            git push origin ${{ github.ref }}
+          fi
 
       - name: Cache plugin dir
         if: steps.diff.outputs.diff
@@ -62,108 +136,141 @@ jobs:
       - name: Setup TFLint
         if: steps.diff.outputs.diff
         uses: terraform-linters/setup-tflint@v1
+        with:
+          tflint_version: v0.34.1
 
       - name: Show version
         if: steps.diff.outputs.diff
         working-directory: ${{ matrix.dir }}
-        run: tflint --version --config=../../common-tflint.hcl
+        run: tflint --version --config=../../../common-tflint.hcl
 
       - name: Init TFLint
         if: steps.diff.outputs.diff
         working-directory: ${{ matrix.dir }}
-        run: tflint --init --config=../../common-tflint.hcl
+        run: tflint --init --config=../../../common-tflint.hcl
 
       - name: Run TFLint
+        id: runTFLint
         if: steps.diff.outputs.diff
         working-directory: ${{ matrix.dir }}
-        run: tflint -f compact --config=../../common-tflint.hcl
-    
-      # 常に最新版を使う
+        run: tflint -f compact --config=../../../common-tflint.hcl
+
+      # TFLintで問題が検出され、PRが存在する場合、結果をPRに投稿する。
+      - name: Comment to pull request(TFLint)
+        id: commentPrTFLint
+        if: steps.diff.outputs.diff && failure() && steps.fail_step.outcome == 'failure' && ( steps.findPr.outputs.pr || github.event.inputs.prNumber )
+        uses: actions/github-script@v6
+        env:
+          PR_NUM: ${{ steps.findPr.outputs.pr }}
+          PR_NUM_INPUT: ${{ github.event.inputs.prNumber }}
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const output = `${{ steps.runTFLint.outputs.stdout }}`;
+            
+            let prNumber;
+            if (!isNaN(parseInt(process.env.PR_NUM))) {
+              prNumber = process.env.PR_NUM;
+            } else if (!isNaN(parseInt(process.env.PR_NUM_INPUT))) {
+              prNumber = process.env.PR_NUM_INPUT;
+            }
+            
+            github.rest.issues.createComment({
+              issue_number: prNumber,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: output
+            })
+
+      # バージョンの管理はインフラ担当が実施する
       - name: Setup terraform
         if: steps.diff.outputs.diff
         uses: hashicorp/setup-terraform@v1
+        with:
+          terraform_version: 1.1.6
       
-      # 強制フォーマット
+      # フォーマットが正しくなければ失敗させる
       - name: Terraform fmt
         id: fmt
         if: steps.diff.outputs.diff
         working-directory: ${{ matrix.dir }}
-        run: terraform fmt
-
-      # CI前にフォーマット済みの場合はエラーになるが処理を継続する
-      - name: Commit .tf files
-        id: commitTf
-        if: steps.diff.outputs.diff
-        working-directory: ${{ matrix.dir }}
-        run: |
-          git config --local user.email  ${{ github.event.pusher.email }}
-          git config --local user.name  ${{ github.event.pusher.name }}
-          git diff
-          git add .
-          git commit -m "fmt: Formated .tf files."
-          git push origin ${{ github.ref }}
-        continue-on-error: true
-        
-      # 初期化。バックエンドは重複しないように動的に設定する
+        run: terraform fmt -recursive -check
+      
+      # 初期化
+      # バックエンドは重複しないように動的に設定する
       - name: Terraform Init
         id: init
-        if: steps.diffFormatedTf.outputs.diff
+        if: steps.diff.outputs.diff
         working-directory: ${{ matrix.dir }}
         run: terraform init -backend-config="key=${{ github.repository }}/${{ matrix.dir }}/terraform.tfstate"
-      
-      - name: Terraform Validate
-        id: validate
-        if: steps.diffFormatedTf.outputs.diff
-        working-directory: ${{ matrix.dir }}
-        run: terraform validate -no-color
-      
+
       - name: Terraform Plan
         id: plan
-        if: steps.diffFormatedTf.outputs.diff
+        if: steps.diff.outputs.diff
         working-directory: ${{ matrix.dir }}
         run: terraform plan -no-color
 
-# 承認～マージまでの間に割り込みでデプロイが発生していないことを確認する
-  # 開発ブランチのpushの段階でチェックするのは、以下の通り。
-  # 1. git pushに必要な情報をコンテキストから抽出するには、originにpushする段階が楽なため
-  # 2. プルリク前からETagをチェックしておき、プルリク作成時に差分があれば弾くため
-  checkETag:
-    runs-on: ubuntu-latest
-    needs: directories
-    strategy:
-      matrix:
-        dir: ${{fromJson(needs.directories.outputs.dir)}} 
-    steps:
-      - uses: actions/checkout@v2
-        name: Checkout
+      # planで問題が検出され、PRが存在する場合、結果をPRに投稿する。
+      - name: Comment to pull request(PLAN)
+        id: commentPrPlan
+        if: steps.diff.outputs.diff && ( steps.findPr.outputs.pr || github.event.inputs.prNumber )
+        uses: actions/github-script@v6
+        env:
+          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+          PR_NUM: ${{ steps.findPr.outputs.pr }}
+          PR_NUM_INPUT: ${{ github.event.inputs.prNumber }}
         with:
-          token: ${{ secrets.GH_PAT }}
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-region: ap-northeast-1
-          role-to-assume: arn:aws:iam::166313796795:role/test-gha
-
-      # 各tfstateファイルのETagを出力
-      # tfstateファイルがなければ空ファイルが生成される
-      - name: Store ETag of tfstate file
-        id: etag
-        working-directory: ${{ matrix.dir }}
-        run: |
-          aws s3api head-object --bucket miyashita-tfstate --key ${{ github.repository }}/${{ matrix.dir }}terraform.tfstate | jq -r .ETag > ./etag-tfstate.txt
-          cat ./etag-tfstate.txt
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+            #### Terraform Validation 🤖\`${{ steps.validate.outputs.stdout }}\`
+            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+            
+            <details><summary>Show Plan</summary>
+            
+            \`\`\`\n
+            ${process.env.PLAN}
+            \`\`\`
+            
+            </details>
+            
+            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ matrix.dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
+            
+            let prNumber;
+            if (!isNaN(parseInt(process.env.PR_NUM))) {
+              prNumber = process.env.PR_NUM;
+            } else if (!isNaN(parseInt(process.env.PR_NUM_INPUT))) {
+              prNumber = process.env.PR_NUM_INPUT;
+            }
+            
+            github.rest.issues.createComment({
+              issue_number: prNumber,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: output
+            })
       
-      # ETagファイルをコミットする
-      # 直前のステップで差分が生じなければエラーになるが受容しスキップする
-      - name: Commit ETag of tfstate file
-        id: commitETag
-        working-directory: ${{ matrix.dir }}
+      - name: Run tfsec with reviewdog output on the PR
+        if: steps.diff.outputs.diff && github.event_name == 'pull_request'
+        uses: reviewdog/action-tfsec@master
+        with:
+          github_token: ${{ secrets.GH_PAT }}
+          working_directory: ${{ matrix.dir }} # Change working directory
+          level: info # Get more output from reviewdog
+          reporter: github-pr-review # Change reviewdog reporter
+          filter_mode: nofilter # Check all files, not just the diff
+          fail_on_error: false # Fail action if errors are found
+          flags: -tee # Add debug flag to reviewdog
+          tfsec_flags: "" # Optional
+
+      - name: send
+        env:
+          CHATWORK_API_KEY: ${{ secrets.CHATWORK_API_KEY }}
         run: |
-          git config --local user.email  ${{ github.event.pusher.email }}
-          git config --local user.name  ${{ github.event.pusher.name }}
-          git diff
-          git add ./etag-tfstate.txt
-          git commit -m "add: Store ETag of tfstate file"
-          git push origin ${{ github.ref }}
-        continue-on-error: true
+          export PR_NUMBER=$(echo $GITHUB_REF | sed -e 's/[^0-9]//g')
+          export PR_URL="https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"
+          echo "[To:4367250]本人" > /tmp/tmp.txt
+          echo "プルリクエストが追加されました。内容を確認と対応をお願いいたします。" >> /tmp/tmp.txt
+          echo "$PR_URL" >> /tmp/tmp.txt
+          curl -X POST -H "X-ChatWorkToken: $CHATWORK_API_KEY" "https://api.chatwork.com/v2/rooms/171332204/messages" -d "body=$(cat /tmp/tmp.txt)"
