Update pr_prod_create_ec2_instance.yml

diff --git a/.github/workflows/pr_prod_create_ec2_instance.yml b/.github/workflows/pr_prod_create_ec2_instance.yml
--- a/.github/workflows/pr_prod_create_ec2_instance.yml
+++ b/.github/workflows/pr_prod_create_ec2_instance.yml
@@ -6,14 +6,41 @@ on:
       - main
     paths:
       - "create-ec2-instance/prod/**"
+  workflow_dispatch:
+    inputs:
+      retry:
+        description: Retry pull request, if it failed.
+        required: true
+        type: boolean
+      prNumber:
+        description: The pull request number that failed.
+        required: true
+        type: number
       
 permissions: 
       id-token: write
       pull-requests: write
       
 jobs:
+  isPrExsit:
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    steps:
+      - name: Check the pull request exists.
+        id: chkPr
+        if: github.event.inputs.retry
+        run: |
+          HTTP_STATE=$(curl -s -I -u miyamiyab:${{ secrets.GH_PAT }} \
+              -H "Accept: application/vnd.github.v3+json" \
+              -o /dev/null -w '%{http_code}\n' \
+              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.inputs.prNumber }})
+          if [ ${HTTP_STATE} -ne 200 ]; then
+            echo "${{ github.repository }}/issues/${{ github.event.inputs.prNumber }} is not found."
+            exit 1
+          fi
   plan:
     runs-on: ubuntu-latest
+    needs: isPrExsit
     timeout-minutes: 5
     strategy:
       matrix:
@@ -51,13 +78,6 @@ jobs:
           PATTERNS: |
             ${{ matrix.dir }}/modules/**/*.tf
             ${{ matrix.dir }}/*.tf
-      
-      - name: Configure AWS Credentials
-        if: steps.diff.outputs.diff
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-region: ap-northeast-1
-          role-to-assume: arn:aws:iam::166313796795:role/test-gha
     
       # 常に最新版を使う
       - name: Setup terraform
@@ -91,11 +111,22 @@ jobs:
         if: steps.diff.outputs.diff
         working-directory: ${{ matrix.dir }}
         run: terraform plan -no-color
+        
+      - name: Find current pull request
+        id: findPr
+        if: steps.diff.outputs.diff
+        uses: jwalton/gh-find-current-pr@v1
+        with:
+          state: all
 
       - name: Comment to pull request
+        id: commentPr
+        if: steps.diff.outputs.diff || github.event.inputs.retry
         uses: actions/github-script@v6
         env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+          PLAN: "terraform\n${{ steps.apply.outputs.stdout }}"
+          PR_NUM: ${{ steps.findPr.outputs.pr }}
+          PR_NUM_INPUT: ${{ github.event.inputs.prNumber }}
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
@@ -113,7 +144,14 @@ jobs:
             </details>
             
             *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ matrix.dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
-              
+            
+            let prNumber;
+            if (!isNaN(parseInt(process.env.PR_NUM))) {
+              prNumber = process.env.PR_NUM;
+            } else if (!isNaN(parseInt(process.env.PR_NUM_INPUT))) {
+              prNumber = process.env.PR_NUM_INPUT;
+            }
+            
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
